title: 'Code For Yokohama'
default_lang: ja
author:
  name: 'Iwao Kobayashi'
  email: info@code4.yokohama
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: ''
